services:
  db:
    image: mysql:8.4.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_USER: database_user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
