CREATE TABLE `sale_estate_facility` (
	                                    `building_id` int(10) unsigned NOT NULL,
	                                    `facility1` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    `facility2` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    `facility3` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    `facility4` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    `facility5` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    `facility6` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    `facility7` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    `facility8` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    `facility9` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    `facility10` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    `facility11` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    `facility12` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    `facility13` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    `facility14` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    `facility15` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    `facility16` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    `facility17` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    `facility18` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    `facility19` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    `facility20` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                    UNIQUE KEY `building_id` (`building_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci