CREATE TABLE `sale_estate_desc` (
	                                `building_id` int(10) unsigned NOT NULL,
	                                `desc1` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc3` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc4` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc5` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc6` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc7` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc8` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc9` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc10` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc11` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc12` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc13` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc14` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc15` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc16` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc17` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc18` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc19` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc20` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc21` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc22` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc23` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc24` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc25` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc26` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc27` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc28` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc29` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc30` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc31` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc32` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc33` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc34` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc35` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc36` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc37` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc38` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc39` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc40` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc41` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc42` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc43` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc44` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc45` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc46` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc47` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc48` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc49` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `desc50` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `flyer` date DEFAULT NULL,
	                                UNIQUE KEY `building_id` (`building_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci