CREATE TABLE `sale_estate_base` (
	                                `id` int(10) unsigned NOT NULL,
	                                `is_recommend` tinyint(1) DEFAULT NULL,
	                                `on_sale` tinyint(1) DEFAULT NULL,
	                                `category` tinyint(1) DEFAULT NULL,
	                                `registered_at` datetime DEFAULT NULL,
	                                `price` decimal(10,1) DEFAULT NULL,
	                                `manage_cost` decimal(10,0) DEFAULT NULL,
	                                `maintenance_cost` decimal(10,0) DEFAULT NULL,
	                                `building_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `building_name_alt` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `zip_code` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `pref` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `city` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `town` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `street` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `address_etc` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `address_alt` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `area` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `access1` varchar(140) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `access2` varchar(140) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `lnd_square` double(10,3) DEFAULT NULL,
	                                `bld_square` double(10,3) DEFAULT NULL,
	                                `room_square` double(10,3) DEFAULT NULL,
	                                `bal_square` double(10,3) DEFAULT NULL,
	                                `first_floor_square` double(10,3) DEFAULT NULL,
	                                `second_floor_square` double(10,3) DEFAULT NULL,
	                                `third_floor_square` double(10,3) DEFAULT NULL,
	                                `fourth_floor_square` double(10,3) DEFAULT NULL,
	                                `total_square` double(10,3) DEFAULT NULL,
	                                `bld_type` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `architecture` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `roofing` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `floor` tinyint(1) DEFAULT NULL,
	                                `plans` smallint(6) DEFAULT NULL,
	                                `plan_s` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `total_floors` int(3) DEFAULT NULL,
	                                `lnd_usage` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `lnd_type` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `urban` varchar(60) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `usage_district1` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `usage_district2` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `limit_square` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `limit_cube` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `current_state` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `law_district1` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `law_district2` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `road_contacts` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `road1_direction` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `road1_contact` double(15,3) DEFAULT NULL,
	                                `road1_width` double(15,3) DEFAULT NULL,
	                                `road1_type` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `road2_direction` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `road2_contact` double(15,3) DEFAULT NULL,
	                                `road2_width` double(15,3) DEFAULT NULL,
	                                `road2_type` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `road3_direction` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `road3_contact` double(15,3) DEFAULT NULL,
	                                `road3_width` double(15,3) DEFAULT NULL,
	                                `road3_type` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `private_road_charge` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `private_road_square` double(32,3) DEFAULT NULL,
	                                `private_road_fee` decimal(10,0) DEFAULT NULL,
	                                `ownership` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `environment` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `upper_build` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `room_amount` decimal(10,0) DEFAULT NULL,
	                                `income_max` decimal(10,0) DEFAULT NULL,
	                                `income_current` decimal(10,0) DEFAULT NULL,
	                                `property_tax` decimal(10,0) DEFAULT NULL,
	                                `national_land_limitation` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `built_date` datetime DEFAULT NULL,
	                                `additional_build` tinyint(1) DEFAULT NULL,
	                                `additional_desc` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `parking` int(11) DEFAULT NULL,
	                                `parking_cars` smallint(6) DEFAULT NULL,
	                                `parking_desc` varchar(60) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `parking_fee` decimal(10,0) DEFAULT NULL,
	                                `catch` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `facility_around` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `elm_school` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `jrh_school` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `trade_term_category` tinyint(4) DEFAULT NULL,
	                                `trade_term` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `trade_period` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `sales_point` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `behavior` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `latitude` double(30,27) DEFAULT NULL,
	                                `longitude` double(30,27) DEFAULT NULL,
	                                `created_at` timestamp NULL DEFAULT current_timestamp(),
	                                `updated_at` timestamp NULL DEFAULT NULL,
	                                `ended_at` datetime DEFAULT NULL,
	                                `search_text` text COLLATE utf8_unicode_ci DEFAULT NULL,
	                                `dealer` smallint(6) DEFAULT NULL,
	                                UNIQUE KEY `id` (`id`),
	                                UNIQUE KEY `sale_estate_base_bk_no_uindex` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci