CREATE TABLE `rent_build_base` (
	                               `id` int(10) unsigned NOT NULL,
	                               `building_name` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `building_kana` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `building_identifier` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `publish_map` tinyint(4) DEFAULT NULL,
	                               `publish_yahoo_map` tinyint(4) DEFAULT NULL,
	                               `publish_room_num` tinyint(4) DEFAULT NULL,
	                               `publish_street` tinyint(4) DEFAULT NULL,
	                               `publish_bk` tinyint(4) DEFAULT NULL,
	                               `bld_square` float DEFAULT NULL,
	                               `lnd_square` float DEFAULT NULL,
	                               `rooms` int(11) DEFAULT NULL,
	                               `category` tinyint(3) NOT NULL,
	                               `zip_code` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `pref` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `city` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `town` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `street` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `address_etc` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `area` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `access1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `access2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `architecture` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `garbage1` varchar(60) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `search_text` text COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `garbage2` varchar(60) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `elm_school` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `elm_school_dist` int(11) DEFAULT NULL,
	                               `elm_school_time` int(11) DEFAULT NULL,
	                               `jrh_school` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `jrh_school_dist` int(11) DEFAULT NULL,
	                               `jrh_school_time` int(11) DEFAULT NULL,
	                               `academy1` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `academy1_dist` int(11) DEFAULT NULL,
	                               `academy2` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `academy2_dist` int(11) DEFAULT NULL,
	                               `near_clinic` int(11) DEFAULT NULL,
	                               `near_super` int(11) DEFAULT NULL,
	                               `near_convenience` int(11) DEFAULT NULL,
	                               `clinic_dist` int(11) DEFAULT NULL,
	                               `super_dist` int(11) DEFAULT NULL,
	                               `near_bus` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `near_bus_time` int(11) DEFAULT NULL,
	                               `near_station` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
	                               `near_station_time` int(11) DEFAULT NULL,
	                               `convenience_dist` int(11) DEFAULT NULL,
	                               `built_date` date DEFAULT NULL,
	                               `floors` int(3) DEFAULT NULL,
	                               `latitude` double DEFAULT NULL,
	                               `longitude` double DEFAULT NULL,
	                               `updated_at` date DEFAULT NULL,
	                               UNIQUE KEY `id` (`id`),
	                               UNIQUE KEY `rent_build_bk_no_uindex` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci